root: true
parserOptions:
  parser: '@typescript-eslint/parser'
  extraFileExtensions: 
    - '.vue'
env:
  browser: true
  es2021: true
  node: true
  'vue/setup-compiler-macros': true
extends:
  - 'plugin:@typescript-eslint/recommended'
  - plugin:vue/vue3-recommended
  - airbnb-base
plugins:
  - only-warn
  - '@typescript-eslint'
  - vue
globals:
  ga: readonly
  cordova: readonly
  __statics: readonly
  __QUASAR_SSR__: readonly
  __QUASAR_SSR_SERVER__: readonly
  __QUASAR_SSR_CLIENT__: readonly
  __QUASAR_SSR_PWA__: readonly
  process: readonly
  Capacitor: readonly
  chrome: readonly
rules:
  no-param-reassign: off
  no-void: off
  no-nested-ternary: off
  max-classes-per-file: off
  no-shadow: off
  '@typescript-eslint/no-shadow': warn
  import/first: off
  import/named: warn
  import/namespace: warn
  import/default: warn
  import/export: warn
  no-undef: off
  import/extensions: off
  import/no-unresolved: off
  import/no-extraneous-dependencies: off
  import/prefer-default-export: off
  prefer-promise-reject-errors: off
  quotes: 
    - warn
    - single
    - avoidEscape: true
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/no-var-requires': off
  no-unused-vars: off
  no-debugger: off
